package org.copy.redis.server.CommandHandler;

import lombok.Getter;

@Getter
public enum constant {
    TTL("TTL"),DEL("DEL"),
    RENAME("RENAME"),EXPIRE("EXPIRE"),
    EXISTS("EXISTS"),TYPE("TYPE"),
    FLUSHALL("FLUSHALL"),//Hash
    HGET("HGET"),HMGET("HMGET"),HGETALL("HGETALL"),HSET("HSET"),HMSET("HMSET"),
    HDEL("HDEL"),HDELALL("HDELALL"),HVALS("HVALS"),HLEN("HLEN"),
    HINCRBYFLOAT("HINCRBYFLOAT"),HINCRBY("HINCRBY"),HKEYS("HKEYS"),HEXISTS("HEXISTS"),//List
    LRANGE("LRANGE"),LINDEX("LINDEX"),LLEN("LLEN"),
    LPUSH("LPUSH"),RPUSH("RPUSH"),LPOP("LPOP"),
    RPOP("RPOP"),LREM("LREM"),LTRIM("LTRIM"),//Set
    SMEMBERS("SMEMBERS"),SISMEMBER("SISMEMBER"),SCARD("SCARD")
    ,SRANDMEMBER("SRANDMEMBER"),SADD("SADD"),SREM("SREM"),SIN("SIN"), //String
    GET("GET"),MGET("MGET"),SET("SET"),MSET("MSET"),
    STRLEN("STRLEN"),APPEND("APPEND"),INCR("INCR"),DECR("DECR"),
    INCRBY("INCRBY"),DECRBY("DECRBY"),SETNX("SETNX"),  //Zset
    ZRANGE("ZRANGE"),ZREVRANGE("ZREVRANGE"),ZSCORE("ZSCORE"),ZRANK("ZRANK")
    ,ZADD("ZADD"),ZREM("ZREM"),ZINCRBY("ZINCRBY"),ZREMRANGEBYRANK("ZREMRANGEBYRANK");
    private String constant;
    constant(String ttl) {
        constant = ttl;
    }

}
